@startuml
ForecasterClient <|-- ForecasterAdaptor
class ForecasterAdaptor {
    com.weather.Forecaster forecaster
}
ForecasterClient <|-- CachingForecasterClient
class CachingForecasterClient {
    ForecasterClient delegate
}
@enduml